version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ramenuser
      - POSTGRES_PASSWORD=ramenpass
    ports:
      - '5432:5432'
volumes:
  postgres:
